version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "rails"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/ssl:/etc/nginx/ssl
    volumes_from:
      - rails

  rails:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - /tmp/shared
    links:
      - postgres
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"

  postgres:
    image: postgres:11
    restart: always
    env_file:
      - $PWD/.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - $PWD/containers/postgres/init:/docker-entrypoint-initdb.d
      - $PWD/containers/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
